name: Weather CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Run unit tests
        run: ./gradlew testDebug

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
        with:
            appId: ${{secrets.FIREBASE_APP_ID}}
            #token: ${{secrets.FIREBASE_TOKEN}}
            serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
            file: app/release/app-release.apk
